name: Reusable - Build and Push to Docker Hub

on:
  workflow_call:
    inputs:
      docker-username:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
    outputs:
      image-uri:
        description: "Imagen completa publicada en Docker Hub"
        value: ${{ jobs.build.outputs.image-uri }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.set-output.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker-username }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.docker-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
            ${{ inputs.docker-username }}/${{ inputs.image-name }}:latest

      - name: Set output
        id: set-output
        run: echo "image=${{ inputs.docker-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}" >> "$GITHUB_OUTPUT"
